name: Deploy CyberShield Backend to EC2


on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@16.171.55.86 << 'EOF'
          cd ~/CYBERSHIELD/backend
          pkill -f alert_service.py || true
          pkill -f detection_api.py || true
          nohup python3 alert_service.py > alert.log 2>&1 &
          nohup python3 detection_api.py > detect.log 2>&1 &
        EOF
